# Generated by Django 5.1.3 on 2025-03-15 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('sigla', models.CharField(max_length=512)),
                ('data_fundacao', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.CharField(max_length=512)),
                ('localizacao', models.CharField(max_length=512)),
                ('morada', models.CharField(max_length=512)),
                ('associacao', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Epoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.IntegerField()),
                ('fim', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('data_nascimento', models.DateField()),
                ('contacto', models.IntegerField()),
                ('tipo', models.CharField(max_length=512)),
                ('funcao', models.CharField(max_length=512)),
                ('foto', models.CharField(max_length=512)),
                ('estado', models.IntegerField()),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.clube')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalao', models.CharField(max_length=512)),
                ('categoria', models.CharField(max_length=512)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.clube')),
                ('epoca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.epoca')),
            ],
        ),
        migrations.CreateModel(
            name='Elemento_Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=512)),
                ('cartao_cidadao', models.CharField(max_length=512)),
                ('data_validade_cc', models.DateField()),
                ('funcao', models.CharField(max_length=512)),
                ('posicao', models.CharField(max_length=512)),
                ('foto', models.CharField(max_length=512)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('estado', models.IntegerField()),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.clube')),
                ('equipas', models.ManyToManyField(to='backendApp.equipa')),
            ],
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.equipa')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exames_medico', models.BooleanField()),
                ('data_exame_medico', models.DateField()),
                ('data_inscricao', models.DateField()),
                ('documentacao', models.BooleanField()),
                ('estado', models.BooleanField()),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.competicao')),
                ('elemento_clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.elemento_clube')),
                ('epoca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.epoca')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('adversario', models.CharField(max_length=512)),
                ('resultado_final', models.CharField(max_length=512)),
                ('localizacao', models.CharField(max_length=512)),
                ('resultado', models.CharField(max_length=512)),
                ('estado', models.IntegerField()),
                ('equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.equipa')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('estado', models.BooleanField()),
                ('foto', models.CharField(max_length=512)),
                ('clubes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.clube')),
            ],
        ),
        migrations.AddField(
            model_name='equipa',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.modalidade'),
        ),
    ]
