# Generated by Django 5.1.3 on 2025-04-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_elemento_clube_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento_clube',
            name='cartao_cidadao',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='elemento_clube',
            name='data_validade_cc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemento_clube',
            name='equipas',
            field=models.ManyToManyField(blank=True, null=True, to='backendApp.equipa'),
        ),
        migrations.AlterField(
            model_name='elemento_clube',
            name='posicao',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
