# Generated by Django 5.1.3 on 2025-04-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_alter_elemento_clube_cartao_cidadao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento_clube',
            name='equipas',
            field=models.ManyToManyField(to='backendApp.equipa'),
        ),
    ]
