# Generated by Django 5.1.3 on 2025-04-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0004_alter_elemento_clube_equipas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elemento_clube',
            old_name='funcao',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='elemento_clube',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemento_clube',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
