# Generated by Django 5.1.3 on 2025-04-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_rename_funcao_elemento_clube_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento_clube',
            name='sexo',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
