# Generated by Django 5.1.3 on 2025-04-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_elemento_clube_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento_clube',
            name='sexo',
            field=models.CharField(max_length=512),
        ),
    ]
