# Generated by Django 5.1.3 on 2025-04-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0007_alter_elemento_clube_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoca',
            name='modalidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendApp.modalidade'),
            preserve_default=False,
        ),
    ]
