# Generated by Django 5.1.3 on 2025-04-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0008_epoca_modalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epoca',
            name='fim',
        ),
        migrations.RemoveField(
            model_name='epoca',
            name='inicio',
        ),
        migrations.AddField(
            model_name='epoca',
            name='fim_epoca',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='epoca',
            name='inicio_epoca',
            field=models.DateField(null=True),
        ),
    ]
