# Generated by Django 5.1.3 on 2025-04-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0009_remove_epoca_fim_remove_epoca_inicio_epoca_fim_epoca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidade',
            name='foto',
        ),
    ]
