# Generated by Django 5.1.3 on 2025-04-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0010_remove_modalidade_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modalidade',
            old_name='clubes',
            new_name='clube',
        ),
    ]
