# Generated by Django 5.1.3 on 2025-04-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0011_rename_clubes_modalidade_clube'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoca',
            name='nome',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
