# Generated by Django 5.1.3 on 2025-04-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0012_epoca_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipa',
            old_name='escalao',
            new_name='nome',
        ),
    ]
