# Generated by Django 5.1.3 on 2025-05-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0013_rename_escalao_equipa_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='competicao',
        ),
    ]
