# Generated by Django 5.1.3 on 2025-05-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0014_remove_inscricao_competicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='competicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendApp.competicao'),
        ),
    ]
