# Generated by Django 5.1.3 on 2025-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0015_jogo_competicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='localizacao',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='resultado',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='resultado_final',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
