# Generated by Django 5.1.3 on 2025-05-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0016_alter_jogo_estado_alter_jogo_localizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
