# Generated by Django 5.1.3 on 2025-05-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0017_alter_inscricao_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='data_exame_medico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='data_inscricao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='documentacao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='exames_medico',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
