# Generated by Django 5.1.3 on 2025-05-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0018_alter_inscricao_data_exame_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='data_exame_medico',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='documentacao',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='cartao_cidadao',
            field=models.FileField(blank=True, null=True, upload_to='documentos/cartoes/'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='exames_medico',
            field=models.FileField(blank=True, null=True, upload_to='documentos/exames/'),
        ),
    ]
