# Generated by Django 5.1.3 on 2025-05-21 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0019_remove_inscricao_data_exame_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('quota_mensal', models.FloatField()),
                ('quota_anual', models.FloatField()),
                ('inscricao', models.FloatField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_quota_mensal', models.FloatField()),
                ('h_quota_anual', models.FloatField()),
                ('h_inscricao', models.FloatField()),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_socio', models.IntegerField()),
                ('data_adesao', models.DateField()),
                ('estado', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.categoria')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_quota', models.CharField(max_length=512)),
                ('mes', models.CharField(blank=True, null=True)),
                ('ano', models.IntegerField()),
                ('prazo_pagamento', models.DateField()),
                ('valor', models.FloatField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('metodo_pagamento', models.CharField(blank=True, null=True)),
                ('estado', models.IntegerField()),
                ('h_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.historico_categoria')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.socio')),
            ],
        ),
    ]
