# Generated by Django 5.1.3 on 2025-05-24 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0020_categoria_historico_categoria_socio_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='clube',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendApp.clube'),
            preserve_default=False,
        ),
    ]
